### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by tiangolo**
Thanks for your code!

I made some changes including a one line install, guessing the username in the ansible-playbook.bat and allowing to do not update ansible every time babun is started (setting a variable in ~/.zshrc), etc.

Feel free to use it if you like it.

Of course you would probably change it to use your repository again.

I make this PR only to let you know the changes I made and that you could use some of them if you like them.

### CODE REVIEW

**Comment by jonathanhle** [comment]
Hi tiangolo!

Thanks for the PR.  

I've switched over to using Ansible on Linux directly now :-), but I'll merge the PR since it might be useful to those still using the repo.

Cheers,
Jonathan

**Comment by tiangolo** [comment]
Great!

One question, just for curiosity, are you using a full linux machine or a virtual machine for controlling?

**Comment by jonathanhle** [comment]
I'm dual booting Ubuntu and Windows.  In Ubuntu when I'm doing testing in Vagrant/need to provision Vagrant with Ansible.  I still spend most of my time in Windows though, so if I'm not provisioning Vagrant, I'll use Ansible in VirtualBox 5.0 (that supports paravirtualization).

**Comment by tiangolo** [comment]
Hmm, interesting, thanks for answering!

**Pull request merged**
